# Generated by Django 4.2.16 on 2024-11-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_license', models.FileField(upload_to='specs')),
                ('number_of_members', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('started_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fail_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('error_detail', models.TextField(max_length=300)),
                ('equipment', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('HL', 'High Level'), ('ML', 'Medium Level'), ('LL', 'Low Level')], max_length=50)),
                ('effect', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
                ('reply', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('std_temperature', models.DecimalField(decimal_places=3, max_digits=10)),
                ('std_humidity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('seasons', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('abv_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('number_managers', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('temperature_change', models.DecimalField(decimal_places=3, max_digits=10)),
                ('humidity_change', models.DecimalField(decimal_places=3, max_digits=10)),
                ('last_update', models.DateTimeField()),
                ('failed', models.BooleanField()),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='region_app.cooperative')),
                ('fail_type', models.ManyToManyField(to='region_app.fail_type')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('expired_date', models.DateTimeField()),
                ('total_quantity_quality', models.IntegerField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region_app.cooperative')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region_app.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region_app.system')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='region_app.cooperative')),
            ],
        ),
        migrations.AddField(
            model_name='cooperative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='region_app.user'),
        ),
    ]
