# Generated by Django 4.2.16 on 2024-11-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region_app.cooperative'),
        ),
    ]
