# Generated by Django 4.2.16 on 2024-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0002_alter_system_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='mission',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='vesion',
            field=models.TextField(null=True),
        ),
    ]
