# Generated by Django 4.2.16 on 2024-11-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0004_alter_system_fail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 8, 28, 4, 307017, tzinfo=datetime.timezone.utc)),
        ),
    ]
