# Generated by Django 4.2.16 on 2024-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0015_rename_location_cooperative_location_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='location_cell',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='location_district',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='location_province',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='location_sector',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='location_village',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
