# Generated by Django 4.2.16 on 2024-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0017_alter_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='mission',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='vesion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
