# Generated by Django 4.2.16 on 2024-12-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0018_alter_cooperative_mission_alter_cooperative_vesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='fail_type',
            field=models.ManyToManyField(to='region_app.fail_type'),
        ),
    ]
