# Generated by Django 4.2.16 on 2024-12-15 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0022_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
