# Generated by Django 4.2.16 on 2024-12-17 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('region_app', '0023_system_resolution_steps_system_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_management',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='system',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
